@echo off
REM PBX Stratos - STRATOS-DailyDigest wrapper for scheduled task
REM
REM Schedule: daily 06:00. Console hidden by silent-run.vbs.
REM
REM REAL VERSION (TODO -- bear-watch tooling expansion):
REM   Aggregate previous-day data and render a markdown digest at
REM   runtime/lab/daily-digest-<YYYY-MM-DD>.md. Contents should be:
REM     - PnL across all bots (realized + unrealized)
REM     - Top trades + worst trades by pct move
REM     - Alerts triggered (severity-grouped)
REM     - Health-check pass rate (the 7-check, 5-min cadence)
REM     - Active strategies + per-strategy tick counts
REM   Reads source data from:
REM     runtime/lab/paper-trades.jsonl, alerts.jsonl, events.jsonl,
REM     runtime/bots/state/<bot>.json
REM
REM STUB (this file):
REM   - Logs heartbeat to _scheduled_logs.
REM   - Writes a placeholder digest md with today's date so the
REM     dashboard's digest viewer (if/when wired) has a file to
REM     render. Real content comes when the user builds it out.

cd /d "%~dp0..\"
call "%~dp0_env-block.bat"
if not exist "%STRATOS_LAB_HOME%\_scheduled_logs" mkdir "%STRATOS_LAB_HOME%\_scheduled_logs"
echo [%DATE% %TIME%] STRATOS-DailyDigest fired (stub) >> "%STRATOS_LAB_HOME%\_scheduled_logs\daily-digest.log"

REM Compute YYYY-MM-DD via PowerShell -- %DATE% format varies by
REM locale, so we use the explicit ISO format from Get-Date.
for /f "tokens=*" %%i in ('powershell -NoProfile -Command "Get-Date -Format yyyy-MM-dd"') do set "TODAY=%%i"

set "DIGEST=%STRATOS_LAB_HOME%\daily-digest-%TODAY%.md"
echo # PBX Stratos -- Daily Digest %TODAY% > "%DIGEST%"
echo. >> "%DIGEST%"
echo Generated by STRATOS-DailyDigest scheduled task at %TIME% (local). >> "%DIGEST%"
echo. >> "%DIGEST%"
echo *Stub implementation.* See bear-watch/run-daily-digest.bat header >> "%DIGEST%"
echo for the real-version TODO list. Build it out as part of the >> "%DIGEST%"
echo bear-watch ops-tooling roadmap. >> "%DIGEST%"
exit /b 0
