@echo off
REM PBX Stratos - STRATOS-CodebaseBackup wrapper for scheduled task
REM
REM Schedule: weekly Sun 03:30. Console hidden by silent-run.vbs.
REM
REM REAL VERSION (TODO):
REM   - git tag -a backup/<YYYY-MM-DD> -m "auto-backup"
REM   - zip the repo to runtime/lab/_backups/codebase-<YYYY-MM-DD>.zip
REM     (excluding node_modules, .venv, runtime/, _context/)
REM   - Optionally git push --tags to a remote
REM
REM STUB (this file):
REM   - Logs heartbeat to _scheduled_logs.
REM   - Writes a git-log snapshot + git-status snapshot to
REM     runtime/lab/_backups/codebase-<YYYY-MM-DD>.txt so the user
REM     has a record of what code was on the machine at backup time.
REM     Recoverable as "I had commit X on date Y" even if the work
REM     tree later changes.

cd /d "%~dp0..\"
call "%~dp0_env-block.bat"
if not exist "%STRATOS_LAB_HOME%\_scheduled_logs" mkdir "%STRATOS_LAB_HOME%\_scheduled_logs"
echo [%DATE% %TIME%] STRATOS-CodebaseBackup fired (stub) >> "%STRATOS_LAB_HOME%\_scheduled_logs\codebase-backup.log"

for /f "tokens=*" %%i in ('powershell -NoProfile -Command "Get-Date -Format yyyy-MM-dd"') do set "TODAY=%%i"
if not exist "%STRATOS_LAB_HOME%\_backups" mkdir "%STRATOS_LAB_HOME%\_backups"
set "BACKUP=%STRATOS_LAB_HOME%\_backups\codebase-%TODAY%.txt"

echo PBX Stratos codebase snapshot -- %TODAY% > "%BACKUP%"
echo Generated by STRATOS-CodebaseBackup scheduled task. >> "%BACKUP%"
echo. >> "%BACKUP%"
echo === git log --oneline -50 === >> "%BACKUP%"
git log --oneline -50 >> "%BACKUP%" 2>&1
echo. >> "%BACKUP%"
echo === git status --short === >> "%BACKUP%"
git status --short >> "%BACKUP%" 2>&1
exit /b 0
