/**
 * Parity harness for the DSL live-feature layer (Phase 2).
 *
 * Run with:  npx tsx --test src/strategies/dsl/features.parity.test.ts
 *
 * GROUND TRUTH: `fixtures/features_parity_fixture.json`, generated by
 * `fixtures/gen_features_fixture.py`. That script fetches a real 3-day
 * window from the public PBX lab API and runs the EXACT `compute_snapshots`
 * math from `bear-scout/runners/wallet-evolve.py`. The fixture bundles both the
 * raw inputs (vault trades, cycles) and the Python-computed snapshots.
 *
 * This harness feeds the identical raw price/cycle series into
 * `LiveSnapshotBuilder`, rebuilds the snapshots, and asserts each field
 * matches the Python value within a float tolerance.
 *
 * KNOWN, DOCUMENTED DIVERGENCE â€” `nearest()` vs append-only buffer.
 * Python's `compute_snapshots` sets each cycle's per-region price via
 * `nearest(region, ts)` â€” the price sample CLOSEST IN TIME, which may be
 * a FUTURE sample. A live bot's buffer is append-only and cannot see the
 * future, so `LiveSnapshotBuilder` uses the latest sample AT-OR-BEFORE
 * the tick. Any field derived from the "current price" (`price`, `spread`,
 * `spread_velocity_15m`, `cheapest`, `rank`, and the `dev_*` numerators)
 * can therefore differ on cycles where the nearest sample was in the
 * future. The harness MEASURES this divergence per field and reports it
 * rather than loosening assertions silently. Fields whose inputs are
 * purely backward-looking (the `dev_*` trailing means, `volatility_60m`,
 * `flow_*`, `hour_utc`, `cycle_*`) are asserted to match exactly.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import {
  LiveSnapshotBuilder,
  SNAPSHOT_REGIONS,
  type RegionPriceSample,
  type SnapshotRegion,
  type WalletView,
} from './features.js';
import { type EngineCycle } from '../../../../../kernel/ts/src/cycle_history.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const FIXTURE = join(HERE, 'fixtures', 'features_parity_fixture.json');

const USDC = 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v';
const MINT_TO_REGION: Record<string, SnapshotRegion> = {
  C751KzNWYDdhELHvZGChnadMhWxpGT8FCGzNWfJJzfh3: 'NYC',
  FXdwYhavxUufiDfEA3kPyVzJSYoQ16euB1EdPfBakXX5: 'CHI',
  Bb7yeJNz1CBsXetysWwHjkk9ospkNExiVTVVKXXWAgDd: 'TOR',
};

interface Fixture {
  generated_at: string;
  days: number;
  pubkey: string | null;
  vault_trades: Array<{
    ts: string;
    token_in: string;
    token_out: string;
    amount_in: number;
    amount_out: number;
  }>;
  cycles: Array<{ ts: string; sold: string | null; bought: string | null }>;
  snapshots: Array<Record<string, number | string | null>>;
}

const tsSec = (iso: string): number => Math.floor(new Date(iso).getTime() / 1000);

/** Derive (region, price) price samples from raw vault trades â€” the exact
 *  reduction `compute_snapshots` performs. */
function priceSamples(fx: Fixture): RegionPriceSample[] {
  const out: RegionPriceSample[] = [];
  for (const vt of fx.vault_trades) {
    const ai = vt.amount_in;
    const ao = vt.amount_out;
    if (ai === 0 || ao === 0) continue;
    let region: SnapshotRegion | undefined;
    let price: number;
    if (vt.token_in === USDC) {
      region = MINT_TO_REGION[vt.token_out];
      price = ai / ao;
    } else {
      region = MINT_TO_REGION[vt.token_in];
      price = ao / ai;
    }
    if (region) out.push({ region, ts: tsSec(vt.ts), price });
  }
  out.sort((a, b) => a.ts - b.ts);
  return out;
}

/** Float-near comparison with a relative+absolute tolerance. */
function near(a: number, b: number, rel = 1e-6, abs = 1e-9): boolean {
  if (a === b) return true;
  return Math.abs(a - b) <= Math.max(abs, rel * Math.max(Math.abs(a), Math.abs(b)));
}

test('parity fixture is present', () => {
  assert.ok(
    existsSync(FIXTURE),
    `fixture missing: ${FIXTURE} â€” regenerate with ` +
      `python3 src/strategies/dsl/fixtures/gen_features_fixture.py`,
  );
});

test('LiveSnapshotBuilder reproduces compute_snapshots field-by-field', () => {
  if (!existsSync(FIXTURE)) {
    // No fixture (offline / not generated) â€” skip with a loud note rather
    // than silently passing. `parity fixture is present` already failed.
    return;
  }
  const fx = JSON.parse(readFileSync(FIXTURE, 'utf-8')) as Fixture;
  const samples = priceSamples(fx);
  assert.ok(samples.length > 0, 'fixture has no price samples');
  assert.ok(fx.snapshots.length > 0, 'fixture has no snapshots');

  const cycles: EngineCycle[] = fx.cycles.map((c) => ({
    ts: tsSec(c.ts),
    sold: c.sold,
    bought: c.bought,
  }));

  // The builder must serve dev_1440m â†’ carry the full 24h window.
  const builder = new LiveSnapshotBuilder({
    predicates: ['dev_60m dev_240m dev_1440m'],
  });
  builder.seedCycles(cycles);

  // The wallet view is empty for this fixture (no pubkey) â€” w_* fields
  // are exercised by the dedicated wallet-state test below.
  const emptyWallet: WalletView = {
    usdc: 0,
    posByRegion: { NYC: 0, CHI: 0, TOR: 0 },
  };

  // Group Python snapshots by (ts, region).
  const pyByKey = new Map<string, Record<string, number | string | null>>();
  const cycleTimestamps: number[] = [];
  const seenTs = new Set<number>();
  for (const s of fx.snapshots) {
    pyByKey.set(`${s.ts}|${s.region}`, s);
    const t = tsSec(s.ts as string);
    if (!seenTs.has(t)) {
      seenTs.add(t);
      cycleTimestamps.push(t);
    }
  }
  cycleTimestamps.sort((a, b) => a - b);

  // Per-field accounting.
  const EXACT_FIELDS = [
    'dev_60m',
    'dev_240m',
    'dev_1440m',
    'dev_velocity_15m',
    'volatility_60m',
    'flow_1',
    'flow_2',
    'flow_5',
    'flow_10',
    'hour_utc',
    'cycle_sold',
    'cycle_bought',
    'rank',
    'cheapest',
  ] as const;
  const NEAREST_SENSITIVE = [
    'price',
    'spread',
    'spread_velocity_15m',
  ] as const;

  const stats: Record<
    string,
    { compared: number; mismatch: number; maxAbsDiff: number }
  > = {};
  for (const f of [...EXACT_FIELDS, ...NEAREST_SENSITIVE]) {
    stats[f] = { compared: 0, mismatch: 0, maxAbsDiff: 0 };
  }
  let snapsCompared = 0;
  let buildsNull = 0;

  // The rigorous parity proof: track, per cycle, whether ALL THREE
  // regions' current prices matched Python. The only structural
  // divergence is `nearest()` (a future-seeing price lookup). So on
  // cycles where every region price matched, EVERY downstream field
  // must match exactly â€” no float budget. Any mismatch there is a real
  // bug. Cycles with a price mismatch are excluded from the hard
  // assertion and counted toward the documented `nearest()` divergence.
  let cyclesPriceClean = 0;
  let cyclesPriceDiverged = 0;
  // Field mismatches observed ON price-clean cycles only (must be 0).
  const cleanMismatch: Record<string, number> = {};
  for (const f of [...EXACT_FIELDS, ...NEAREST_SENSITIVE]) cleanMismatch[f] = 0;

  // Feed price samples incrementally up to each cycle ts, then build.
  let sIdx = 0;
  for (const ct of cycleTimestamps) {
    while (sIdx < samples.length && samples[sIdx]!.ts <= ct) {
      builder.observe([samples[sIdx]!], samples[sIdx]!.ts);
      sIdx++;
    }
    const built = builder.build(ct, emptyWallet, []);
    if (built == null) {
      buildsNull++;
      continue;
    }
    // First pass: is this cycle price-clean â€” i.e. for every region,
    // Python and the live builder agree on the current price? A region
    // that Python priced (via a possibly-future nearest() sample) but the
    // live append-only buffer could NOT price is itself a price
    // divergence, so such a cycle is NOT price-clean.
    let priceClean = true;
    for (const region of SNAPSHOT_REGIONS) {
      const py = findPyAt(pyByKey, ct, region);
      const live = built[region];
      const pyHas = !!py && typeof py.price === 'number';
      const liveHas = !!live && typeof live.price === 'number';
      if (pyHas !== liveHas) {
        priceClean = false; // one side priced this region, the other did not
        continue;
      }
      if (!pyHas) continue; // neither priced it â€” no divergence
      if (!near(py!.price as number, live!.price as number)) {
        priceClean = false;
      }
    }
    if (priceClean) cyclesPriceClean++;
    else cyclesPriceDiverged++;

    for (const region of SNAPSHOT_REGIONS) {
      const py = findPyAt(pyByKey, ct, region);
      const live = built[region];
      if (!py || !live) continue;
      snapsCompared++;

      for (const f of [...EXACT_FIELDS, ...NEAREST_SENSITIVE]) {
        const pv = py[f];
        const lv = live[f];
        const st = stats[f]!;
        st.compared++;
        let mismatched = false;
        if (typeof pv === 'number' && typeof lv === 'number') {
          if (!near(pv, lv)) {
            mismatched = true;
            st.maxAbsDiff = Math.max(st.maxAbsDiff, Math.abs(pv - lv));
          }
        } else if (pv !== lv) {
          mismatched = true;
        }
        if (mismatched) {
          st.mismatch++;
          if (priceClean) cleanMismatch[f]!++;
        }
      }
    }
  }

  // â”€â”€ Report â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  console.log(
    `\n  parity: ${snapsCompared} snapshots compared ` +
      `(${buildsNull} cycle(s) un-buildable: <2 priceable regions at-or-before ts)`,
  );
  console.log('  â”€â”€ backward-looking fields (asserted EXACT) â”€â”€');
  for (const f of EXACT_FIELDS) {
    const st = stats[f]!;
    const pct = st.compared ? ((st.mismatch / st.compared) * 100).toFixed(2) : '0';
    console.log(
      `    ${f.padEnd(20)} ${st.compared - st.mismatch}/${st.compared} match` +
        (st.mismatch ? `  (${pct}% diff, maxÎ”=${st.maxAbsDiff.toExponential(2)})` : ''),
    );
  }
  console.log('  â”€â”€ nearest()-sensitive fields (divergence MEASURED) â”€â”€');
  for (const f of NEAREST_SENSITIVE) {
    const st = stats[f]!;
    const pct = st.compared ? ((st.mismatch / st.compared) * 100).toFixed(2) : '0';
    console.log(
      `    ${f.padEnd(20)} ${st.compared - st.mismatch}/${st.compared} match` +
        (st.mismatch ? `  (${pct}% diverge, maxÎ”=${st.maxAbsDiff.toExponential(2)})` : ''),
    );
  }
  console.log(
    `\n  cycles price-clean (all 3 region prices == Python): ` +
      `${cyclesPriceClean}/${cyclesPriceClean + cyclesPriceDiverged}` +
      `  |  price-diverged (nearest() saw a future sample): ${cyclesPriceDiverged}`,
  );
  console.log('');

  // â”€â”€ PARITY GUARANTEE 1 â€” purely backward-looking fields â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  // `volatility_60m`, `flow_*`, `hour_utc`, `cycle_*` do NOT depend on
  // the current price (only on the trailing window / cycle list). They
  // MUST match Python exactly on EVERY snapshot â€” no exceptions.
  const HARD_EXACT = [
    'volatility_60m',
    'flow_1',
    'flow_2',
    'flow_5',
    'flow_10',
    'hour_utc',
    'cycle_sold',
    'cycle_bought',
  ] as const;
  for (const f of HARD_EXACT) {
    const st = stats[f]!;
    assert.equal(
      st.mismatch,
      0,
      `field ${f} must match Python exactly â€” ${st.mismatch}/${st.compared} ` +
        `mismatched (maxÎ”=${st.maxAbsDiff})`,
    );
  }

  // â”€â”€ PARITY GUARANTEE 2 â€” price-dependent fields, conditioned â”€â”€â”€â”€â”€â”€â”€â”€â”€
  // `price`, `spread`, `dev_*`, `rank`, `cheapest`, `spread_velocity_15m`
  // all derive from the current price. The ONLY thing that makes the live
  // price differ from Python is `nearest()` seeing a future sample. So on
  // every cycle where all 3 region prices matched Python ("price-clean"),
  // these fields MUST match exactly too. A nonzero count here is a REAL
  // bug (e.g. mean-vs-median, n-vs-(n-1) stdev), not the nearest() effect.
  for (const f of [
    'dev_60m', 'dev_240m', 'dev_1440m', 'dev_velocity_15m',
    'rank', 'cheapest', 'spread', 'spread_velocity_15m', 'price',
  ]) {
    assert.equal(
      cleanMismatch[f],
      0,
      `field ${f} mismatched on ${cleanMismatch[f]} price-clean cycle(s) â€” ` +
        `this is NOT attributable to the documented nearest() divergence ` +
        `and indicates a real parity bug`,
    );
  }

  // Sanity: the harness actually exercised price-clean cycles (otherwise
  // GUARANTEE 2 is vacuous).
  assert.ok(
    cyclesPriceClean > 0,
    'no price-clean cycles â€” GUARANTEE 2 would be vacuous',
  );
  assert.ok(snapsCompared > 0, 'no snapshots were compared');
});

/** Find the Python snapshot for a numeric instant + region (offset-agnostic). */
function findPyAt(
  pyByKey: Map<string, Record<string, number | string | null>>,
  ct: number,
  region: string,
): Record<string, number | string | null> | undefined {
  return (
    pyByKey.get(`${new Date(ct * 1000).toISOString()}|${region}`) ??
    findPy(pyByKey, ct, region)
  );
}

/** Find the Python snapshot for a numeric instant + region (offset-agnostic). */
function findPy(
  pyByKey: Map<string, Record<string, number | string | null>>,
  ct: number,
  region: string,
): Record<string, number | string | null> | undefined {
  for (const [k, v] of pyByKey) {
    const [iso, r] = k.split('|');
    if (r === region && iso && Math.floor(new Date(iso).getTime() / 1000) === ct) {
      return v;
    }
  }
  return undefined;
}

test('wallet-state (w_*) features reconstruct from the bot trade log', () => {
  // Synthetic, deterministic â€” exercises the w_* path the fixture (no
  // pubkey) doesn't cover. Verifies the same semantics the Python
  // reconstruct_wallet_state / state_at produce.
  const builder = new LiveSnapshotBuilder({ predicates: ['dev_60m'] });
  builder.seedCycles([
    { ts: 1_000_000, sold: 'NYC', bought: 'Chicago' },
  ]);
  // Two priceable regions are required for build() to return non-null.
  const t0 = 1_000_000;
  builder.observe(
    [
      { region: 'NYC', ts: t0 - 100, price: 0.05 },
      { region: 'CHI', ts: t0 - 100, price: 0.06 },
    ],
    t0 - 100,
  );

  const wallet: WalletView = {
    usdc: 42.5,
    posByRegion: { NYC: 12, CHI: 0, TOR: 0 },
  };
  const trades = [
    { ts: t0 - 7200, side: 'buy' as const, region: 'CHI' as const },
    { ts: t0 - 3600, side: 'sell' as const, region: 'CHI' as const },
    { ts: t0 - 1800, side: 'buy' as const, region: 'NYC' as const },
  ];

  const built = builder.build(t0, wallet, trades);
  assert.ok(built, 'expected a non-null snapshot set');
  const nyc = built!.NYC!;

  // Balances straight from the wallet view.
  assert.equal(nyc.w_usdc, 42.5);
  assert.equal(nyc.w_pos_self, 12); // NYC's own position
  assert.equal(nyc.w_pos_NYC, 12);
  assert.equal(nyc.w_pos_CHI, 0);
  assert.equal(nyc.w_pos_TOR, 0);

  // Most recent trade <= t0 is the NYC buy at t0-1800.
  assert.equal(nyc.w_last_action, 'buy');
  assert.equal(nyc.w_last_region, 'NYC');
  assert.equal(nyc.w_sec_since_any_trade, 1800);
  // w_n_trades == index of that trade (Python state_at semantics): 3rd
  // trade, 0-based index 2.
  assert.equal(nyc.w_n_trades, 2);
  // w_sec_since_self_trade for NYC: the NYC buy at t0-1800.
  assert.equal(nyc.w_sec_since_self_trade, 1800);

  // For CHI: most recent CHI trade is the sell at t0-3600.
  const chi = built!.CHI!;
  assert.equal(chi.w_pos_self, 0);
  assert.equal(chi.w_sec_since_self_trade, 3600);
  // w_last_* are shared (most recent ANY trade) â†’ still the NYC buy.
  assert.equal(chi.w_last_region, 'NYC');

  // No trades at all â†’ null cooldowns, 0 count.
  const builtNoTrades = builder.build(t0, wallet, []);
  const nycNT = builtNoTrades!.NYC!;
  assert.equal(nycNT.w_n_trades, 0);
  assert.equal(nycNT.w_last_action, null);
  assert.equal(nycNT.w_last_region, null);
  assert.equal(nycNT.w_sec_since_any_trade, null);
  assert.equal(nycNT.w_sec_since_self_trade, null);
});

test('flow reproduces the Python CHI/TOR label-mismatch quirk', () => {
  // The cycles API returns 'Chicago'/'Toronto' (full names) but 'NYC'
  // (short code). Python flow() compares against short codes, so CHI/TOR
  // flow is structurally 0. The live layer must reproduce this.
  const builder = new LiveSnapshotBuilder({ predicates: ['dev_60m'] });
  const t = 2_000_000;
  builder.seedCycles([
    { ts: t - 300, sold: 'NYC', bought: 'Chicago' },
    { ts: t - 200, sold: 'Toronto', bought: 'NYC' },
    { ts: t - 100, sold: 'Chicago', bought: 'Toronto' },
  ]);
  builder.observe(
    [
      { region: 'NYC', ts: t - 50, price: 0.05 },
      { region: 'CHI', ts: t - 50, price: 0.06 },
      { region: 'TOR', ts: t - 50, price: 0.07 },
    ],
    t - 50,
  );
  const built = builder.build(t, { usdc: 0, posByRegion: { NYC: 0, CHI: 0, TOR: 0 } }, [])!;
  // NYC: bought in cycle[1] (+1), sold in cycle[0] (-1) â†’ flow over all 3 = 0.
  // flow_10 covers all 3 cycles: +1 (bought c1) -1 (sold c0) = 0.
  assert.equal(built.NYC!.flow_10, 0);
  // flow_1 covers cycles [idx-1 .. idx] = c1,c2: NYC bought in c1 â†’ +1.
  assert.equal(built.NYC!.flow_1, 1);
  // CHI / TOR: API labels are 'Chicago'/'Toronto' â€” never == 'CHI'/'TOR'.
  // So their flow is always 0 regardless of cycle direction.
  for (const f of ['flow_1', 'flow_2', 'flow_5', 'flow_10'] as const) {
    assert.equal(built.CHI![f], 0, `CHI ${f} must be 0 (label mismatch)`);
    assert.equal(built.TOR![f], 0, `TOR ${f} must be 0 (label mismatch)`);
  }
});
