/**
 * Tests for the DSL interpreter port.
 *
 * Run with:  npx tsx --test src/strategies/dsl/interpreter.test.ts
 *
 * The core correctness guarantee is the differential suite: it loads
 * `fixtures/dsl_cases.json` (generated by `fixtures/gen_fixtures.py`
 * from the real Python evaluator) and asserts `safeEvaluate` matches
 * Python for every curated edge case.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import {
  evaluatePredicate,
  safeEvaluate,
  validatePredicate,
  stripWalletTermsFromEntry,
  DslParseError,
  ALIASES,
  KNOWN_FEATURES,
  type Snapshot,
} from './interpreter.js';

const HERE = dirname(fileURLToPath(import.meta.url));

interface FixtureCase {
  predicate: string;
  snapshot: Snapshot;
  snapshotKey: string;
  expected: boolean;
}

const fixtures: FixtureCase[] = JSON.parse(
  readFileSync(join(HERE, 'fixtures', 'dsl_cases.json'), 'utf8'),
);

test('differential: safeEvaluate matches Python for every fixture', () => {
  assert.ok(fixtures.length > 0, 'fixtures must be non-empty');
  const mismatches: string[] = [];
  for (const c of fixtures) {
    const got = safeEvaluate(c.predicate, c.snapshot);
    if (got !== c.expected) {
      mismatches.push(
        `  [${c.snapshotKey}] ${JSON.stringify(c.predicate)} ` +
          `expected ${c.expected}, got ${got}`,
      );
    }
  }
  assert.equal(
    mismatches.length,
    0,
    `${mismatches.length}/${fixtures.length} differential mismatches:\n` +
      mismatches.join('\n'),
  );
});

// --- direct semantic checks (not just differential) ---

const SNAP: Snapshot = {
  region: 'NYC',
  price: 1.25,
  spread: 0.08,
  cheapest: 'CHI',
  rank: 2,
  w_pos_self: 3,
  w_last_action: null,
};

test('AND/OR are uppercase-literal only', () => {
  // lowercase does not split: "price > 1.0 and ..." is one bare-ish atom
  // -> regex matches "price" "> " "1.0 and spread < 0.1" -> rhs null -> false
  assert.equal(evaluatePredicate('price > 1.0 and spread < 0.1', SNAP), false);
  assert.equal(evaluatePredicate('price > 1.0 AND spread < 0.1', SNAP), true);
  assert.equal(evaluatePredicate('price > 9.0 or spread < 0.1', SNAP), false);
  assert.equal(evaluatePredicate('price > 9.0 OR spread < 0.1', SNAP), true);
});

test('NOT is case-insensitive', () => {
  assert.equal(evaluatePredicate('NOT price > 9.0', SNAP), true);
  assert.equal(evaluatePredicate('not price > 9.0', SNAP), true);
  assert.equal(evaluatePredicate('NoT price > 9.0', SNAP), true);
});

test('(a) AND (b) outer parens are NOT stripped', () => {
  // If parens were naively stripped this would become "price > 1.0) AND (spread"
  assert.equal(
    evaluatePredicate('(price > 1.0) AND (spread < 0.1)', SNAP),
    true,
  );
  assert.equal(
    evaluatePredicate('(price > 9.0) OR (spread < 0.1)', SNAP),
    true,
  );
});

test('fully-wrapped parens are stripped', () => {
  assert.equal(evaluatePredicate('(price > 1.0)', SNAP), true);
  assert.equal(evaluatePredicate('((price > 1.0))', SNAP), true);
});

test('bare term with null/missing value resolves true', () => {
  assert.equal(evaluatePredicate('w_last_action', SNAP), true);
  assert.equal(evaluatePredicate('totally_unknown_token', SNAP), true);
});

test('bare numeric term truthiness', () => {
  assert.equal(evaluatePredicate('1', SNAP), true);
  assert.equal(evaluatePredicate('0', SNAP), false);
});

test('null operand semantics', () => {
  assert.equal(evaluatePredicate('w_last_action == "buy"', SNAP), false);
  assert.equal(evaluatePredicate('w_last_action != "buy"', SNAP), true);
  // ordering ops on null -> false
  assert.equal(evaluatePredicate('w_last_action > 1', SNAP), false);
  assert.equal(evaluatePredicate('w_last_action < 1', SNAP), false);
});

test('aliases resolve to snapshot fields', () => {
  assert.equal(evaluatePredicate('this == "NYC"', SNAP), true);
  assert.equal(evaluatePredicate('self == "NYC"', SNAP), true);
  assert.equal(evaluatePredicate('held == "NYC"', SNAP), true);
  assert.equal(evaluatePredicate('cheapest_region == "CHI"', SNAP), true);
});

test('case-insensitive string equality', () => {
  assert.equal(evaluatePredicate('region == "nyc"', SNAP), true);
  assert.equal(evaluatePredicate('region != "nyc"', SNAP), false);
});

test('non-numeric ordering throws DslParseError', () => {
  assert.throws(
    () => evaluatePredicate('region < "NYC"', SNAP),
    DslParseError,
  );
  // safeEvaluate swallows it to false
  assert.equal(safeEvaluate('region < "NYC"', SNAP), false);
});

test('safeEvaluate returns false on malformed input', () => {
  assert.equal(safeEvaluate('"a" >= "b"', SNAP), false);
});

// --- validatePredicate (deploy-time gate) ---

test('validatePredicate accepts well-formed predicates', () => {
  assert.deepEqual(validatePredicate('price > 1.0'), { ok: true });
  assert.deepEqual(
    validatePredicate('(price > 1.0 AND spread < 0.1) OR rank == 2'),
    { ok: true },
  );
  assert.deepEqual(validatePredicate('NOT w_pos_self > 0'), { ok: true });
  assert.deepEqual(validatePredicate('this == "NYC"'), { ok: true });
  assert.deepEqual(validatePredicate('w_pos_NYC_self > 0'), { ok: true });
});

test('validatePredicate rejects unknown identifiers (fail-closed)', () => {
  const r = validatePredicate('made_up_feature > 1.0');
  assert.equal(r.ok, false);
});

test('validatePredicate rejects empty / whitespace', () => {
  assert.equal(validatePredicate('').ok, false);
  assert.equal(validatePredicate('   ').ok, false);
});

test('validatePredicate rejects unbalanced parens', () => {
  assert.equal(validatePredicate('(price > 1.0').ok, false);
  assert.equal(validatePredicate('price > 1.0)').ok, false);
});

test('validatePredicate enforces max length', () => {
  const long = 'price > 1.0 OR '.repeat(200) + 'price > 1.0';
  assert.equal(validatePredicate(long).ok, false);
});

test('validatePredicate enforces max paren depth', () => {
  const deep = '('.repeat(40) + 'price > 1.0' + ')'.repeat(40);
  assert.equal(validatePredicate(deep).ok, false);
});

test('validatePredicate enforces max term count', () => {
  const many = Array.from({ length: 120 }, () => 'price > 1.0').join(' AND ');
  assert.equal(validatePredicate(many).ok, false);
});

test('validatePredicate allows quoted string + numeric literals', () => {
  assert.deepEqual(validatePredicate('region == "NYC"'), { ok: true });
  assert.deepEqual(validatePredicate('price == 1.5'), { ok: true });
});

test('KNOWN_FEATURES includes alias keys', () => {
  for (const k of Object.keys(ALIASES)) {
    assert.ok(KNOWN_FEATURES.has(k), `missing alias key ${k}`);
  }
  assert.ok(KNOWN_FEATURES.has('w_sec_since_self_trade'));
});

// --- security: no dynamic code execution in the interpreter source ---

test('interpreter source contains no dynamic code execution', () => {
  const src = readFileSync(join(HERE, 'interpreter.ts'), 'utf8');
  // Strip comments so explanatory prose mentioning these words elsewhere
  // does not trip the check; we only care about live code.
  const codeOnly = src
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .replace(/\/\/.*$/gm, '');
  // Forbidden tokens are assembled from fragments so the literal
  // strings never appear in this file's source either.
  const fn = 'Funct' + 'ion';
  const ev = 'ev' + 'al';
  const forbidden = [
    ev + '(',
    'new ' + fn,
    fn + '(',
    'node:' + 'vm',
    "'" + 'vm' + "'",
  ];
  for (const token of forbidden) {
    assert.equal(
      codeOnly.includes(token),
      false,
      `interpreter source must not contain ${JSON.stringify(token)}`,
    );
  }
});

// ── stripWalletTermsFromEntry ──────────────────────────────────────────
// Entry predicates must gate on MARKET conditions only. Wallet-state
// (w_*) conjuncts describe the decoded wallet's own activity and a fresh
// bot can never satisfy them — they deadlock entry forever.

test('stripWalletTermsFromEntry: drops w_* conjuncts from a flat AND chain', () => {
  const r = stripWalletTermsFromEntry(
    'rank == 0 AND dev_240m < -0.04 AND w_n_trades > 5 AND w_usdc > 100',
  );
  assert.equal(r.predicate, 'rank == 0 AND dev_240m < -0.04');
  assert.deepEqual(r.stripped, ['w_n_trades > 5', 'w_usdc > 100']);
});

test('stripWalletTermsFromEntry: a market-only predicate is unchanged', () => {
  const r = stripWalletTermsFromEntry('rank == 0 AND dev_1440m < -0.073');
  assert.equal(r.predicate, 'rank == 0 AND dev_1440m < -0.073');
  assert.deepEqual(r.stripped, []);
});

test('stripWalletTermsFromEntry: a top-level OR predicate is left untouched', () => {
  const p = 'w_usdc > 100 OR rank == 0';
  const r = stripWalletTermsFromEntry(p);
  assert.equal(r.predicate, p);
  assert.deepEqual(r.stripped, []);
});

test('stripWalletTermsFromEntry: an all-wallet predicate strips to empty', () => {
  const r = stripWalletTermsFromEntry('w_n_trades > 5 AND w_usdc > 100');
  assert.equal(r.predicate, '');
  assert.deepEqual(r.stripped, ['w_n_trades > 5', 'w_usdc > 100']);
});
