#!/usr/bin/env node
/**
 * scripts/reset-fresh.mjs
 *
 * Reset the dashboard back to a fresh first-open state for walkthroughs
 * + demos. Wipes progress data (decoded wallets, paper trades, alerts,
 * events, achievements) but PRESERVES installation state (the wallet
 * mnemonic in ~/.pbx-bots/local.env, the Helius URL in .env, the
 * personality picks in user-profile.json, the .tooling/ready.json
 * install marker, node_modules, .venv).
 *
 * Usage:
 *   node scripts/reset-fresh.mjs           # full reset, with backup
 *   node scripts/reset-fresh.mjs --no-backup   # skip backup (faster)
 *   npm run reset                          # alias
 *
 * After running, open the dashboard at
 *   http://localhost:8787/dashboard/fresh
 * which wipes the localStorage flags (onboarding-done, nav-view,
 * etc.) AND redirects to /dashboard so the tour fires from scratch.
 * Keeps your BOT_API_TOKEN so you don't have to re-paste it.
 *
 * Safe to run while pm2 is up. Restarts the bear-watch-server
 * process at the end so any in-memory caches drop.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync, rmSync,
         readdirSync, copyFileSync, lstatSync, statSync } from 'node:fs';
import { homedir } from 'node:os';
import { join, basename } from 'node:path';
import { execSync } from 'node:child_process';

const HOME       = homedir();
const PBX_LAB    = join(HOME, '.pbx-lab');
const PBX_BOTS   = join(HOME, '.pbx-bots');
const REPO_ROOT  = join(import.meta.dirname || new URL('.', import.meta.url).pathname, '..');
const NO_BACKUP  = process.argv.includes('--no-backup');
const TIMESTAMP  = new Date().toISOString().replace(/[:.]/g, '-');
const BACKUP_DIR = join(PBX_LAB, `_reset-backup-${TIMESTAMP}`);

// ── What to wipe (PROGRESS data, not installation) ─────────────────────
// Files reset to empty. The file stays in place so anything that watches
// for its existence (alerts.jsonl, paper-trade-heartbeat) still works.
const FILES_TO_TRUNCATE = [
  'alerts.jsonl',
  'events.jsonl',
  'bot-registry.jsonl',
  'tracked-wallets.jsonl',
  'nav-history.jsonl',
  'backtest-signal.csv',
];

// Files deleted outright. Will be regenerated by the running system as
// needed.
const FILES_TO_DELETE = [
  'achievements.json',
  'aqi-snapshot.json',
  // daily-digest-*.md handled separately (glob match)
];

// Subdirectories whose CONTENTS get cleared (the dir itself stays).
const DIRS_TO_CLEAR = [
  'wallets',           // decoded wallet runs
  'paper-trades',      // paper-trade history
  'evolve-jobs',       // evolution runs in progress
  'exports',           // user-exported data
];

// user-profile.json: surgical edit, not delete. Keeps the user's
// personality + tech_level + quiz answers, just resets the achievements
// tracking fields.
const PROFILE_FIELDS_TO_RESET = {
  achievements_unlocked: [],
  total_unlocked: 0,
  last_achievement_at: null,
  roadmap_level: 1,
};

// ── Helpers ────────────────────────────────────────────────────────────

function logStep(...args) { console.log('  ', ...args); }
function logHeader(s)     { console.log('\n  \x1b[36m' + s + '\x1b[0m'); }
function logOk(s)         { console.log('  \x1b[32m✓\x1b[0m', s); }
function logWarn(s)       { console.log('  \x1b[33m!\x1b[0m', s); }

function safeExists(p) {
  try { return existsSync(p); } catch { return false; }
}

function copyToBackup(src, name) {
  if (NO_BACKUP) return;
  if (!safeExists(src)) return;
  try {
    mkdirSync(BACKUP_DIR, { recursive: true });
    const stat = lstatSync(src);
    if (stat.isDirectory()) {
      // Recursive copy
      const dst = join(BACKUP_DIR, name);
      mkdirSync(dst, { recursive: true });
      for (const entry of readdirSync(src)) {
        const sub = join(src, entry);
        const sst = lstatSync(sub);
        if (sst.isDirectory()) copyToBackup(sub, join(name, entry));
        else { try { copyFileSync(sub, join(BACKUP_DIR, name, entry)); } catch {} }
      }
    } else if (stat.isFile()) {
      copyFileSync(src, join(BACKUP_DIR, name));
    }
  } catch (e) {
    logWarn(`could not back up ${src}: ${e.message}`);
  }
}

function truncateFile(p) {
  try {
    if (safeExists(p)) {
      copyToBackup(p, basename(p));
      writeFileSync(p, '', { mode: 0o600 });
      logOk(`truncated ${p}`);
    }
  } catch (e) {
    logWarn(`could not truncate ${p}: ${e.message}`);
  }
}

function deleteFile(p) {
  try {
    if (safeExists(p)) {
      copyToBackup(p, basename(p));
      rmSync(p, { force: true });
      logOk(`deleted ${p}`);
    }
  } catch (e) {
    logWarn(`could not delete ${p}: ${e.message}`);
  }
}

function clearDirContents(dir) {
  try {
    if (!safeExists(dir)) return;
    copyToBackup(dir, basename(dir));
    for (const entry of readdirSync(dir)) {
      const p = join(dir, entry);
      try { rmSync(p, { recursive: true, force: true }); } catch {}
    }
    logOk(`cleared contents of ${dir}/`);
  } catch (e) {
    logWarn(`could not clear ${dir}: ${e.message}`);
  }
}

function deleteGlob(dir, pattern) {
  try {
    if (!safeExists(dir)) return;
    for (const entry of readdirSync(dir)) {
      if (pattern.test(entry)) {
        const p = join(dir, entry);
        copyToBackup(p, entry);
        try { rmSync(p, { force: true }); logOk(`deleted ${p}`); } catch {}
      }
    }
  } catch {}
}

function resetProfileFields() {
  const profilePath = join(PBX_LAB, 'user-profile.json');
  if (!safeExists(profilePath)) {
    logWarn('user-profile.json not found, skipping profile reset');
    return;
  }
  try {
    copyToBackup(profilePath, 'user-profile.json');
    const profile = JSON.parse(readFileSync(profilePath, 'utf8'));
    for (const [key, value] of Object.entries(PROFILE_FIELDS_TO_RESET)) {
      profile[key] = value;
    }
    profile.last_updated = new Date().toISOString();
    writeFileSync(profilePath, JSON.stringify(profile, null, 2) + '\n', { mode: 0o600 });
    logOk(`reset achievements fields in user-profile.json (kept personality_id="${profile.personality_id}" + the 5 quiz answers)`);
  } catch (e) {
    logWarn(`could not reset profile: ${e.message}`);
  }
}

// ── Main ──────────────────────────────────────────────────────────────

function main() {
  logHeader('PBX Stratos — dashboard reset');
  console.log(`     home:       ${HOME}`);
  console.log(`     pbx-lab:    ${PBX_LAB}`);
  console.log(`     pbx-bots:   ${PBX_BOTS}  (mnemonic PRESERVED)`);
  console.log(`     backup:     ${NO_BACKUP ? '(skipped, --no-backup)' : BACKUP_DIR}`);

  logHeader('1. Truncating jsonl/csv progress files');
  for (const f of FILES_TO_TRUNCATE) truncateFile(join(PBX_LAB, f));

  logHeader('2. Deleting cached snapshots + achievement state');
  for (const f of FILES_TO_DELETE) deleteFile(join(PBX_LAB, f));
  deleteGlob(PBX_LAB, /^daily-digest-.*\.md$/);

  logHeader('3. Clearing progress subdirectories');
  for (const d of DIRS_TO_CLEAR) clearDirContents(join(PBX_LAB, d));

  logHeader('4. Surgically resetting user-profile.json achievement fields');
  resetProfileFields();

  logHeader('5. Restarting pm2 server (drops in-memory caches)');
  // Stratos-only restart, exact app name. Any other installation on
  // the same machine uses a different pm2 app name; this can never
  // touch it.
  try {
    execSync('pm2 restart bear-watch-server-stratos', { stdio: 'ignore' });
    logOk('bear-watch-server-stratos restarted');
  } catch {
    logWarn('could not restart pm2 (server may not be managed by pm2 — that\'s fine)');
  }

  logHeader('Done.');
  console.log(`
  Next: open the dashboard at the FRESH URL — it clears your browser's
  tour-state localStorage and redirects you to a clean dashboard:

      http://localhost:8787/dashboard/fresh

  Your BOT_API_TOKEN stays in localStorage so you don't have to
  re-paste it. The onboarding tour will fire from step 1, the
  Achievements page will show 0 of 14 done in Section 1, and the
  Strategies page will be empty.

  ${NO_BACKUP ? 'No backup was made.' : `Backup of everything that was wiped: ${BACKUP_DIR}`}
`);
}

main();
